# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon_app', '0002_auto_20171016_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
