# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_words', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Dictionary',
        ),
    ]
