# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 23:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, and periods', regex='[ .a-zA-Z]+')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, and periods', regex='[ .a-zA-Z]+')])),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
