# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 23:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=50, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, underscore, and periods (no spaces)', regex='[_.a-zA-Z0-9]+')]),
            preserve_default=False,
        ),
    ]
