# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, underscore, and periods (no spaces)', regex='[_.a-zA-Z0-9]+')])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, and periods', regex='[ .a-zA-Z]+')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, and periods', regex='[ .a-zA-Z]+')])),
                ('email', models.EmailField(max_length=100)),
                ('birthdate', models.DateField(blank=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
