# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20171017_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
